'use client'

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/K5qWxgoRUOu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Judson } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogContent, Dialog, DialogClose } from "@/components/ui/dialog"
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { updateHabit } from "@/app/actions"
import { MountainIcon } from "./icons"
import { Habit } from "../db"

export function EditHabitDialog({ habit }: { habit: Habit }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button className="flex items-center gap-2" variant="primary">
        <FileEditIcon className="h-5 w-5" />
        </Button>
      </DialogTrigger>
      <DialogContent className="w-full max-w-md mx-auto p-4 md:p-10">
        <div className="flex flex-col min-h-[100dvh]">
          <header className="px-4 lg:px-6 h-14 flex items-center">
            <Link className="flex items-center justify-center" href="#">
              <MountainIcon className="h-6 w-6" />
              <span className="sr-only">Habit Tracker</span>
            </Link>
          </header>
          <main className="flex-1 bg-gray-100 dark:bg-gray-800 p-4 md:p-10 flex items-center justify-center">
            <form action={(formData: FormData) => updateHabit(habit.habitId, formData.get("habitName") as string ) } >
              <div className="space-y-4">
                <h1 className="text-3xl font-bold">Edit habit</h1>
                <div className="space-y-2">
                  <Label htmlFor="habitName">Habit Name</Label>
                  <Input id="habitName" minLength={1} type="text" required={true} name="habitName" placeholder={habit.habitName} />
                </div>
                <div className="flex">
                  <DialogClose type="submit">Update</DialogClose>
                </div>
              </div>
            </form>
          </main>
        </div>
      </DialogContent>
    </Dialog>
  )
}

function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  )
}
