/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vvW3t6W5Clf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Judson } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Header } from "@/components/header"
import { CreateHabitDialog } from "./create-habit-dialog"
import { Session } from "@auth/core/types"
import { getHabits, Habit } from "@/db"
import { HabitCard } from "./habit-card"

export async function Habits({ session }: { session: Session} ) {
  const habits = await getHabits(session.user?.id || '')
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <Header/>
      <main className="flex-1 bg-gray-100 dark:bg-gray-800 p-4 md:p-10">
        <div className="max-w-6xl mx-auto grid gap-8">
          <div className="grid md:grid-cols-[1fr_auto] items-center gap-4">
            <h1 className="text-3xl font-bold">Your Habits</h1>
            <CreateHabitDialog opened={habits.length === 0} />
          </div>
          <div className="grid gap-4">
            {habits.sort((h1, h2) => h1.habitName < h2.habitName ? -1 : 1).map((habit: Habit) => (
              <HabitCard habit={habit} key={habit.habitId}/>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}
