/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vvW3t6W5Clf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Judson } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Header } from "@/components/header"
import { CreateHabitDialog } from "./create-habit-dialog"
import { Session } from "@auth/core/types"
import { getHabits, Habit } from "@/db"

export async function Habits({ session }: { session: Session} ) {
  const habits = await getHabits(session.user?.id || '')
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <Header/>
      <main className="flex-1 bg-gray-100 dark:bg-gray-800 p-4 md:p-10">
        <div className="max-w-6xl mx-auto grid gap-8">
          <div className="grid md:grid-cols-[1fr_auto] items-center gap-4">
            <h1 className="text-3xl font-bold">Your Habits</h1>
            <CreateHabitDialog opened={false} userId={session.user?.id || ''}/>
          </div>
          <div className="grid gap-4">
            {habits.sort((h1, h2) => h1.habitName < h2.habitName ? -1 : 1).map((habit: Habit) => (
              <Card key={habit.habitId}>
                <CardHeader>
                  <CardTitle>{habit.habitName}</CardTitle>
                  <CardDescription>Some description</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="text-2xl font-bold">60%</div>
                    <Button size="icon" variant="outline">
                      <CheckIcon className="h-5 w-5" />
                      <span className="sr-only">Track habit</span>
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}

