/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KKuSUvGQhaj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { signIn } from "@/auth"

export function LandingPage() {
  return (
    <main className="flex flex-col min-h-screen">
      <section className="w-full flex-1 py-20 md:py-32 lg:py-40 bg-gray-50 dark:bg-gray-900">
        <div className="container px-4 md:px-6 lg:px-8 mx-auto max-w-5xl text-center">
          <div className="space-y-6">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
              Stay on top of your habits
            </h1>
            <p className="text-lg text-gray-600 dark:text-gray-400 max-w-3xl mx-auto">
              Our habit tracking app helps you build and maintain healthy routines with ease. Get started today and take
              control of your daily life.
            </p>
            <form
                action={async () => {
                  "use server"
                  await signIn("google")
                }}
              >
                <Button type="submit" className="inline-flex items-center justify-center gap-2" variant="outline">
                  <ChromeIcon className="h-5 w-5" />
                  Sign in with Google
                </Button>
              </form>
          </div>
        </div>
      </section>
    </main>
  )
}

function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}
