/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/c8GwdyR0XoF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { signIn } from "@/auth"

export function LandingPage() {
  return (
    <main className="flex flex-col gap-6 p-4 md:p-8">
      <section className="bg-gray-100 dark:bg-gray-800 py-12 md:py-24 lg:py-32">
        <div className="container grid items-center justify-center gap-6 px-4 md:px-6">
          <div className="space-y-3 text-center">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Unlock Your Potential with Our Wellness Tracker
            </h1>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Effortlessly track your daily meditation, exercise, and reading habits. Gain insights to improve your
              overall well-being.
            </p>
            <div>
              <form
                action={async () => {
                  "use server"
                  await signIn("google")
                }}
              >
                <Button type="submit" className="inline-flex items-center justify-center gap-2" variant="outline">
                  <ChromeIcon className="h-5 w-5" />
                  Sign in with Google
                </Button>
              </form>
            </div>
          </div>
        </div>
      </section>
    </main>
  )
}

function ChromeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}
