/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QlZAscHGSiB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

export function LoadingPage() {
  return (
    <>
      <div className="flex items-center justify-center h-screen">
        <div className="space-y-4">
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 shadow-md">
            <div className="animate-pulse flex space-x-4">
              <div className="rounded-full bg-gray-300 dark:bg-gray-600 h-10 w-10" />
              <div className="flex-1 space-y-6 py-1">
                <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded" />
                <div className="space-y-3">
                  <div className="grid grid-cols-3 gap-4">
                    <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded col-span-2" />
                    <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded col-span-1" />
                  </div>
                  <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded" />
                </div>
              </div>
            </div>
          </div>
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 shadow-md">
            <div className="animate-pulse flex space-x-4">
              <div className="rounded-full bg-gray-300 dark:bg-gray-600 h-10 w-10" />
              <div className="flex-1 space-y-6 py-1">
                <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded" />
                <div className="space-y-3">
                  <div className="grid grid-cols-3 gap-4">
                    <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded col-span-2" />
                    <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded col-span-1" />
                  </div>
                  <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded" />
                </div>
              </div>
            </div>
          </div>
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 shadow-md">
            <div className="animate-pulse flex space-x-4">
              <div className="rounded-full bg-gray-300 dark:bg-gray-600 h-10 w-10" />
              <div className="flex-1 space-y-6 py-1">
                <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded" />
                <div className="space-y-3">
                  <div className="grid grid-cols-3 gap-4">
                    <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded col-span-2" />
                    <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded col-span-1" />
                  </div>
                  <div className="h-2 bg-gray-300 dark:bg-gray-600 rounded" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
